FROM colynn/maven:3.6.0-jdk-8-alpine-sh-settings as build-stage
WORKDIR /app
COPY . .
RUN mvn clean install -U >/dev/null

FROM colynn/alpine-oraclejdk8:slim as production-stage
COPY --from=build-stage /app/target/api.jar /app/api.jar
WORKDIR /app
ENV JAVA_OPTS="-XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Xms1536m -Xmx1536m -Xmn768m -Xss256k"
ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar api.jar
